name: Xuxemons

services:
  db:
    container_name: xuxemons_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: xuxemons
      MYSQL_USER: xuxemons_user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xuxemons_network

# Podriamos aÃ±adir un healthcheck

  backend:
    container_name: xuxemons_laravel
    image: php:8.3-apache
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    networks:
      - xuxemons_network
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && 
      a2enmod rewrite &&
      sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf &&
      apache2-foreground"

  frontend:
    container_name: xuxemons_angular
    image: node:20
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - xuxemons_network
    command: >
     bash -c "npm install && npm start -- --host 0.0.0.0"

volumes:
  db_data:

networks:
  xuxemons_network:
    driver: bridge